/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea_1;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Heiner
 */
public class JFVentanaPrincipal extends javax.swing.JFrame {
    
    int paso=1;
    int posicionMemoria = 0;
    String rutaArchivo;
    Boolean archivoCargado;

    /**
     * Creates new form JFVentanaPrincipal
     */
    public JFVentanaPrincipal() {
        initComponents();
        this.archivoCargado=false;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCargarArchivo = new javax.swing.JLabel();
        tfCargarArchivo = new javax.swing.JTextField();
        btCargarArchivo = new javax.swing.JButton();
        btAnalizarArchivo = new javax.swing.JButton();
        btSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelInstrucciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea_1");
        setPreferredSize(new java.awt.Dimension(820, 730));

        lbCargarArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCargarArchivo.setText("Cargar archivo:");

        tfCargarArchivo.setEditable(false);
        tfCargarArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btCargarArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btCargarArchivo.setText("Cargar");
        btCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarArchivoActionPerformed(evt);
            }
        });

        btAnalizarArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btAnalizarArchivo.setText("Analizar");
        btAnalizarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalizarArchivoActionPerformed(evt);
            }
        });

        btSiguiente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btSiguiente.setText("Siguiente");
        btSiguiente.setEnabled(false);
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        panelInstrucciones.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane2.setViewportView(panelInstrucciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCargarArchivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCargarArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAnalizarArchivo)))
                        .addGap(0, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCargarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCargarArchivo)
                    .addComponent(btAnalizarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnalizarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalizarArchivoActionPerformed
        if(archivoCargado){
            try {
                Operaciones.muestraContenido(rutaArchivo);
                posicionMemoria=Operaciones.posicionMemoria;
                btSiguienteActionPerformed(evt); // Funcion del boton Siguiente.
                btSiguiente.setEnabled(true);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error de archivo",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Cargue un archivo para analizar", "Carga de archivo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAnalizarArchivoActionPerformed

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        if(paso<=Operaciones.numeroInstrucciones && posicionMemoria<99){
            JPPaso ejecucion=new JPPaso(paso,posicionMemoria);
            panelInstrucciones.add(ejecucion);
            panelInstrucciones.updateUI();
            paso++;
            posicionMemoria++;
        }else{
            JOptionPane.showMessageDialog(this, "No hay más instrucciones o se llegó al final de la memoria.", "No hay más instrucciones",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btSiguienteActionPerformed

    private void btCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarArchivoActionPerformed
        JFileChooser cargador=new JFileChooser();
        cargador.setFileFilter(new FileNameExtensionFilter("ASM", "asm"));
        cargador.showOpenDialog(this);
        File archivo=cargador.getSelectedFile();
        if(archivo!=null){
            tfCargarArchivo.setText(archivo.getName());
            rutaArchivo=archivo.getPath();
            archivoCargado=true;
        }
    }//GEN-LAST:event_btCargarArchivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnalizarArchivo;
    private javax.swing.JButton btCargarArchivo;
    private javax.swing.JButton btSiguiente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCargarArchivo;
    private javax.swing.JPanel panelInstrucciones;
    private javax.swing.JTextField tfCargarArchivo;
    // End of variables declaration//GEN-END:variables
}
